services:
  - type: web
    name: ecommerce-project
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: ""
    healthCheckPath: /
